# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SocialLogin' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SocialLogin
	pod “FBSDKCoreKit”
	pod “FBSDKLoginKit”
  target 'SocialLogin-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SocialLoginTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

